apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chisel-operator
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: chisel-operator
  project: default
  sources:
    - chart: chisel-operator
      repoURL: oci://ghcr.io/fyralabs/chisel-operator/chisel-operator
      targetRevision: ~0
      helm:
        valuesObject:
          loadBalancerClass: chisel
    - path: chisel-operator
      repoURL: https://github.com/sglre6355/argocd-apps
      targetRevision: HEAD
      directory:
        recurse: true
    - path: applications/chisel
      repoURL: https://github.com/sglre6355/external-secrets-manifests
      targetRevision: HEAD
      directory:
        recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
