apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-cluster-secret-stores
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  project: default
  source:
    path: cluster-secret-stores
    repoURL: https://github.com/sglre6355/external-secrets-manifests
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
